const erpData = {
  todayClassId: "dataAnalysisReport",
  categories: ["전체", "AI 기초", "보고서·탐구", "이미지", "영상", "데이터", "진로", "홍보·마케팅", "기타"],
  courses: [
    {
      id: "dataAnalysisReport",
      title: "AI 데이터 분석 기반 주제탐구보고서 작성",
      shortTitle: "주제탐구보고서",
      description: "탐구 주제를 정하고 실제 데이터를 분석·시각화한 뒤 학교 제출용 보고서 PDF를 완성합니다.",
      category: "보고서·탐구",
      tags: ["탐구", "보고서", "데이터", "그래프", "PDF"],
      tools: ["ChatGPT", "Semantic Scholar", "Datawrapper", "Google Sheets"],
      lessons: 4,
      duration: "4차시",
      type: "실습형",
      resultType: "주제탐구보고서 PDF",
      thumbnail: "assets/courses/class1.png",
      studentUrl: "sessions/topic-research-report/",
      reportUrl: "sessions/topic-research-report/report/",
      featured: true,
      isToday: true,
      createdAt: "2026-07-15",
      sortOrder: 1,
      target: ["중학생", "고등학생"],
      status: "active",
    },
    {
      id: "droneExpert",
      title: "AI 드론전문가 진로탐구 수업",
      shortTitle: "드론전문가",
      description: "드론 산업과 직업 세계를 탐색하고 AI를 활용해 진로 탐구 결과물을 정리합니다.",
      category: "진로",
      tags: ["드론", "진로", "직업", "항공", "AI"],
      tools: ["ChatGPT", "Gemini", "Claude"],
      lessons: 4,
      duration: "4차시",
      type: "실습형",
      resultType: "진로탐구 결과물",
      thumbnail: "assets/courses/class2.png",
      studentUrl: "",
      reportUrl: "",
      featured: true,
      isToday: false,
      createdAt: "2026-07-17",
      sortOrder: 2,
      target: ["중학생", "고등학생"],
      status: "active",
    },
    {
      id: "careerRecordActivity",
      title: "AI를 활용하는 생기부·세특 진로활동",
      shortTitle: "생기부·세특",
      description: "관심 분야 활동을 정리하고 세특과 진로활동에 연결되는 결과물을 기획합니다.",
      category: "진로",
      tags: ["생기부", "세특", "진로", "활동정리", "AI"],
      tools: ["ChatGPT", "Gemini", "Claude"],
      lessons: 4,
      duration: "4차시",
      type: "실습형",
      resultType: "진로활동 정리 자료",
      thumbnail: "assets/courses/class3.png",
      studentUrl: "",
      reportUrl: "",
      featured: true,
      isToday: false,
      createdAt: "2026-07-17",
      sortOrder: 3,
      target: ["중학생", "고등학생"],
      status: "active",
    },
    {
      id: "youtubeCreator",
      title: "AI 유튜브 크리에이터 프로젝트",
      shortTitle: "유튜브 크리에이터",
      description: "기획, 대본, 썸네일, 영상 구성까지 AI로 짧은 콘텐츠 제작 흐름을 실습합니다.",
      category: "영상",
      tags: ["유튜브", "크리에이터", "대본", "썸네일", "영상"],
      tools: ["ChatGPT", "Canva", "CapCut"],
      lessons: 4,
      duration: "4차시",
      type: "프로젝트형",
      resultType: "숏폼 또는 유튜브 기획안",
      thumbnail: "assets/courses/class4.png",
      studentUrl: "",
      reportUrl: "",
      featured: false,
      isToday: false,
      createdAt: "2026-07-17",
      sortOrder: 4,
      target: ["중학생", "고등학생"],
      status: "active",
    },
    {
      id: "financeCoaching",
      title: "청소년 금융코칭 프로젝트",
      shortTitle: "금융코칭",
      description: "예산, 저축, 소비 습관을 AI와 함께 분석하고 생활 속 금융 계획을 세웁니다.",
      category: "데이터",
      tags: ["금융", "경제", "소비", "저축", "청소년"],
      tools: ["ChatGPT", "Google Sheets"],
      lessons: 4,
      duration: "4차시",
      type: "실습형",
      resultType: "개인 금융 계획서",
      thumbnail: "assets/courses/class5.png",
      studentUrl: "",
      reportUrl: "",
      featured: false,
      isToday: false,
      createdAt: "2026-07-17",
      sortOrder: 5,
      target: ["중학생", "고등학생"],
      status: "active",
    },
    {
      id: "cardNews",
      title: "생성형 AI를 활용한 카드뉴스 제작",
      shortTitle: "카드뉴스 제작",
      description: "주제를 조사하고 핵심 메시지를 시각적으로 정리해 카드뉴스 결과물을 만듭니다.",
      category: "이미지",
      tags: ["카드뉴스", "디자인", "홍보", "이미지", "AI"],
      tools: ["ChatGPT", "Canva"],
      lessons: 4,
      duration: "4차시",
      type: "실습형",
      resultType: "카드뉴스 이미지 세트",
      thumbnail: "assets/courses/class6.png",
      studentUrl: "",
      reportUrl: "",
      featured: true,
      isToday: false,
      createdAt: "2026-07-17",
      sortOrder: 6,
      target: ["중학생", "고등학생"],
      status: "active",
    },
    {
      id: "shortsVideo",
      title: "AI를 활용한 숏폼 영상 제작",
      shortTitle: "숏폼 영상",
      description: "짧은 영상의 메시지, 장면, 자막을 기획하고 AI 도구로 숏폼 콘텐츠를 제작합니다.",
      category: "영상",
      tags: ["숏폼", "릴스", "영상", "자막", "AI"],
      tools: ["ChatGPT", "CapCut"],
      lessons: 4,
      duration: "4차시",
      type: "실습형",
      resultType: "30초 내외 숏폼 영상",
      thumbnail: "assets/courses/class7.png",
      studentUrl: "",
      reportUrl: "",
      featured: false,
      isToday: false,
      createdAt: "2026-07-17",
      sortOrder: 7,
      target: ["중학생", "고등학생"],
      status: "active",
    },
    {
      id: "emoticonCreator",
      title: "AI 이모티콘 크리에이터",
      shortTitle: "이모티콘 제작",
      description: "캐릭터 콘셉트를 만들고 감정별 이모티콘 세트를 기획·제작합니다.",
      category: "이미지",
      tags: ["이모티콘", "캐릭터", "이미지", "디자인", "AI"],
      tools: ["ChatGPT", "Image AI", "Canva"],
      lessons: 4,
      duration: "4차시",
      type: "프로젝트형",
      resultType: "이모티콘 콘셉트 세트",
      thumbnail: "assets/courses/class8.png",
      studentUrl: "",
      reportUrl: "",
      featured: false,
      isToday: false,
      createdAt: "2026-07-17",
      sortOrder: 8,
      target: ["중학생", "고등학생"],
      status: "active",
    },
    {
      id: "hotelPromo",
      title: "AI 홍보영상 제작 프로젝트",
      shortTitle: "AI 홍보영상 만들기",
      description: "생성형 AI로 학교, 지역, 행사, 브랜드, 제품, 서비스를 소개하는 30~60초 홍보영상을 기획하고 완성합니다.",
      category: "영상",
      tags: ["AI 영상", "홍보", "마케팅", "스토리보드", "이미지 생성", "영상 편집"],
      tools: ["ChatGPT", "HeyGen", "Google Flow", "CapCut"],
      lessons: 4,
      duration: "4교시",
      type: "프로젝트형",
      resultType: "30~60초 AI 홍보영상",
      thumbnail: "assets/courses/class9.png",
      studentUrl: "sessions/ai-practice/?lesson=hotelPromo",
      reportUrl: "",
      featured: true,
      isToday: false,
      createdAt: "2026-07-03",
      sortOrder: 9,
      target: ["중학생", "고등학생"],
      status: "active",
    },
    {
      id: "localBrandCampaign",
      title: "우리 동네 브랜드 AI 홍보캠페인 제작",
      shortTitle: "동네 브랜드 캠페인",
      description: "지역 가게, 명소, 공공 캠페인을 조사하고 AI로 홍보 캠페인 자료를 제작합니다.",
      category: "홍보·마케팅",
      tags: ["지역", "브랜드", "홍보", "캠페인", "마케팅"],
      tools: ["ChatGPT", "Canva", "CapCut"],
      lessons: 4,
      duration: "4차시",
      type: "프로젝트형",
      resultType: "홍보 캠페인 기획안",
      thumbnail: "assets/courses/class10.png",
      studentUrl: "",
      reportUrl: "",
      featured: false,
      isToday: false,
      createdAt: "2026-07-17",
      sortOrder: 10,
      target: ["중학생", "고등학생"],
      status: "active",
    },
    {
      id: "scienceCsPrep",
      title: "고교학점제 및 수능대비특강",
      shortTitle: "학습 대비 특강",
      description: "학습 목표를 점검하고 AI를 활용해 교과 개념, 탐구 활동, 진로 계획을 정리합니다.",
      category: "AI 기초",
      tags: ["고교학점제", "수능", "학습", "진로", "AI"],
      tools: ["ChatGPT", "Gemini", "Claude"],
      lessons: 4,
      duration: "4차시",
      type: "이론·실습",
      resultType: "학습 점검 자료",
      thumbnail: "assets/courses/class11.png",
      studentUrl: "",
      reportUrl: "",
      featured: false,
      isToday: false,
      createdAt: "2026-07-17",
      sortOrder: 11,
      target: ["중학생", "고등학생"],
      status: "active",
    },
  ],
};

window.erpData = erpData;
