const erpData = {
  instructor: {
    name: "강사",
    modeLabel: "강사 모드",
    systemName: "LoreAX Class ERP",
  },
  todayClass: {
    courseId: "ai-video",
    sessionId: "hotel-promo",
    lessonId: "hotelPromo",
    courseTitle: "AI 영상 제작 실습",
    sessionTitle: "AI 호텔 홍보영상 제작",
    moduleType: "AI 실습형 수업",
    status: "준비 완료",
    duration: "4교시",
    recommendedScenes: "4장면",
    finalOutput: "30~40초 호텔 홍보영상",
    thumbnail: "assets/hotel-ai-video-class-hero.png",
    launchUrl: "sessions/ai-practice/index.html?lesson=hotelPromo",
    presentUrl: "present/index.html?lesson=hotelPromo",
  },
  dashboardCards: [
    {
      id: "today",
      title: "오늘의 수업",
      description: "오늘 진행할 수업과 차시를 확인하고 바로 수업을 시작합니다.",
      status: "실행 가능",
      buttonLabel: "AI 실습형 수업 실행하기",
      url: "sessions/ai-practice/index.html?lesson=hotelPromo",
    },
    {
      id: "courses",
      title: "과목 관리",
      description: "강좌, 과목, 차시 템플릿을 관리합니다.",
      status: "준비 중",
      buttonLabel: "준비 중",
      url: "",
    },
    {
      id: "resources",
      title: "수업 자료실",
      description: "프롬프트, 예시 이미지, 영상 자료, 수업 파일을 관리합니다.",
      status: "준비 중",
      buttonLabel: "준비 중",
      url: "",
    },
    {
      id: "feedback",
      title: "결과물 / 피드백",
      description: "학생 결과물 제출, 리뷰, 피드백을 관리합니다.",
      status: "준비 중",
      buttonLabel: "준비 중",
      url: "",
    },
  ],
  courses: [
    {
      courseId: "ai-video",
      courseTitle: "AI 영상 제작 실습",
      description: "이미지 생성, 영상 생성, 편집 도구를 활용해 짧은 홍보영상을 제작하는 실습형 수업입니다.",
      sessions: [
        {
          sessionId: "hotel-promo",
          lessonId: "hotelPromo",
          sessionTitle: "AI 호텔 홍보영상 제작",
          type: "AI 실습형 수업",
          duration: "4교시",
          finalOutput: "30~40초 호텔 홍보영상",
          status: "준비 완료",
          launchUrl: "sessions/ai-practice/index.html?lesson=hotelPromo",
          presentUrl: "present/index.html?lesson=hotelPromo",
        },
        {
          sessionId: "tourism-promo",
          lessonId: "tourismPromo",
          sessionTitle: "AI 관광지 소개영상 제작",
          type: "AI 실습형 수업",
          duration: "4교시",
          finalOutput: "30~40초 관광지 소개영상",
          status: "샘플 준비 중",
          launchUrl: "sessions/ai-practice/index.html?lesson=tourismPromo",
          presentUrl: "present/index.html?lesson=tourismPromo",
        },
        {
          sessionId: "product-ad",
          lessonId: "productAd",
          sessionTitle: "AI 제품 광고영상 제작",
          type: "AI 실습형 수업",
          duration: "4교시",
          finalOutput: "20~30초 제품 광고영상",
          status: "샘플 준비 중",
          launchUrl: "sessions/ai-practice/index.html?lesson=productAd",
          presentUrl: "present/index.html?lesson=productAd",
        },
      ],
    },
    {
      courseId: "ai-data-research",
      courseTitle: "AI 데이터 분석 주제탐구",
      description: "AI를 활용해 탐구 주제를 정하고, 데이터를 분석·시각화한 뒤 최종 보고서를 PDF로 완성하는 4차시 수업입니다.",
      sessions: [
        {
          sessionId: "dataAnalysisReport",
          lessonId: "dataAnalysisReport",
          sessionTitle: "AI 데이터 분석 기반 주제탐구보고서 작성",
          type: "AI 실습형 수업",
          duration: "4교시",
          finalOutput: "주제탐구보고서 PDF",
          status: "준비 완료",
          launchUrl: "sessions/ai-practice/index.html?lesson=dataAnalysisReport",
          presentUrl: "present/index.html?lesson=dataAnalysisReport",
        },
      ],
    },
  ],
};
